### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by suheyla2** [MunzerDw/NODF-HashEnc#1]
This line outputs NaN (after masking is applied) because of division by zero:

https://github.com/MunzerDw/NODF-HashEnc/blob/a5d4b891fb0a9b2e2b22cd9b0c04bbff6f8e9370/utility/utility.py#L21 

We can replace this line with the following:
```
epsilon = 1e-10  # A small value to prevent division by zero
data_b0_mean = np.mean(data_b0, axis=3)[:, :, :, np.newaxis]
data_b0 = np.divide(data_b0, data_b0_mean + epsilon)
```

**Comment by MunzerDw** [comment]
Thank you for the suggestion.

Dividing by epsilon could cause numbers to explode, giving an unreliable standard deviation at the points where b0 is 0. Removing those points does not influence the end result by a lot since there are only a few.
