### ISSUE TITLE
 shls.py is in the same folder with utility.py, so no need for utility.utility

### ISSUE THREAD

**Issue by suheyla2** [MunzerDw/NODF-HashEnc#2]
https://github.com/MunzerDw/NODF-HashEnc/blob/a5d4b891fb0a9b2e2b22cd9b0c04bbff6f8e9370/utility/shls.py#L9

replace these lines with 
`from utility import ( `

**Comment by MunzerDw** [comment]
Fixed with the most recent push on the main branch. Please use "python utility/shls.py" to run the file.
